### ISSUE TITLE
Save terminology table doesn't contain edits made to subtitles

### ISSUE THREAD

**Issue by aburkleaux-amazon** [aws-samples/aws-media-insights-content-localization#128]
The save terminology page should show source language and target language pairs for edits made by the user to subtitles.  However, the table is always blank.

Fix test_app.py when this is fixed

 FIXME - Issue #128 Save terminology table doesn't contain edits made to subtitles

**Comment by ianwow** [comment]
Edits to the terminology table are incorrectly being saved to the `customTerminologyUnsaved` dict with keys `original_phrase` and `new_phrase`. (This is a bug due to copy and paste from custom vocabs). The correct key should be `this.sourceLanguageCode` and `this.selected_lang_code`. I made this change in https://github.com/aws-samples/aws-media-insights-content-localization/pull/142

However, I'm not sure what value to put for the `this.sourceLanguageCode` value since we'd have to do a reverse translation to know that.
